name = "mp4-to-gif-pro"
main = ".open-next/worker.js"
compatibility_date = "2025-01-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# [vars]
# Environment variables should be set via Cloudflare dashboard or wrangler secrets
# NEXT_PUBLIC_GA_ID = "your-ga-id"
# NEXT_PUBLIC_CLARITY_PROJECT_ID = "your-clarity-id"

# Production environment
[env.production]
name = "mp4-to-gif-pro-production"

# Preview/staging environment
[env.preview]
name = "mp4-to-gif-pro-preview"
